# Generated by Django 5.1.1 on 2025-03-08 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('ncode', models.CharField(max_length=10)),
                ('phonenumber', models.CharField(max_length=11)),
                ('rtahsil', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('arr', models.CharField(max_length=100)),
            ],
        ),
    ]
